# Generated by Django 5.2.11 on 2026-04-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône Lucide", max_length=50)),
                ('couleur', models.CharField(default='#4F46E5', help_text='Code hex', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_bon_plan',
            field=models.BooleanField(default=False, help_text='Marquer comme bon plan'),
        ),
        migrations.AddField(
            model_name='event',
            name='pourcentage_reduction',
            field=models.PositiveIntegerField(blank=True, help_text='% de réduction (calculé automatiquement)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prix_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix avant réduction (si bon plan)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='events.categorie'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='evenements', to='events.tag'),
        ),
    ]
