# Generated by Django 5.2.11 on 2026-04-27 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_categorie_tag_event_is_bon_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_bon_plan',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pourcentage_reduction',
        ),
        migrations.RemoveField(
            model_name='event',
            name='prix_original',
        ),
        migrations.AddField(
            model_name='categorie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_validee',
            field=models.BooleanField(default=True, help_text='False si proposée par un organisateur en attente de validation admin'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='proposee_par',
            field=models.ForeignKey(blank=True, help_text='Organisateur qui a proposé cette catégorie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_proposees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='motif_refus',
            field=models.TextField(blank=True, help_text='Motif de refus (si applicable)'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(default='#4F46E5', help_text='Code hexadécimal (ex: #4F46E5)', max_length=7),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, help_text="Nom de l'icône Lucide (ex: Music, Utensils)", max_length=50),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, help_text='Calculé automatiquement depuis les types de billets', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix minimum (calculé depuis les types de billets)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publie', 'Publié'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='TypeBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Standard, VIP, Early Bird', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Ce qui est inclus dans ce billet', max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_bon_plan', models.BooleanField(default=False)),
                ('prix_original', models.DecimalField(blank=True, decimal_places=2, help_text='Prix avant réduction (si bon plan)', max_digits=10, null=True)),
                ('pourcentage_reduction', models.PositiveIntegerField(blank=True, help_text='% de réduction (calculé automatiquement)', null=True)),
                ('capacite', models.PositiveIntegerField(help_text='Nombre de places disponibles pour ce type')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_billets', to='events.event')),
            ],
            options={
                'verbose_name': 'Type de billet',
                'verbose_name_plural': 'Types de billets',
                'ordering': ['ordre', 'prix'],
            },
        ),
    ]
