# Generated by Django 5.2.11 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_bon_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_evenement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lieu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
