# Generated by Django 5.2.11 on 2026-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='brouillon', max_length=20),
        ),
    ]
