# Generated by Django 5.2.11 on 2026-07-08 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='confirmee', max_length=20)),
                ('total_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('code_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.reservation')),
                ('type_billet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='events.typebillet')),
            ],
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'viewed_at'], name='events_even_event_i_f73daa_idx'), models.Index(fields=['user', 'event'], name='events_even_user_id_e3a409_idx')],
            },
        ),
    ]
