# Generated by Django 5.2.11 on 2026-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_remise_fidelite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remise_fidelite_pct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
