# Generated by Django 5.2.11 on 2026-06-08 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='latitude',
            new_name='current_latitude',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='longitude',
            new_name='current_longitude',
        ),
        migrations.AddField(
            model_name='user',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('register', 'Inscription'), ('login', 'Connexion'), ('manual', 'Mise à jour manuelle'), ('event_view', 'Consultation événement')], default='login', max_length=20)),
                ('ville_detectee', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', '-detected_at'], name='users_userl_user_id_67cef5_idx')],
            },
        ),
    ]
