# Generated by Django 5.2.11 on 2026-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_latitude_user_current_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Emoji représentatif', max_length=10)),
                ('is_official', models.BooleanField(default=True, help_text="True = intérêt officiel d'Eventu. False = créé par un utilisateur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_official', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='interets',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.interet'),
        ),
    ]
