# Generated by Django 5.2.11 on 2026-06-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_statut'),
        ('users', '0004_interet_user_interets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organisateur',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DemandeOrganisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisation', models.CharField(max_length=200)),
                ('type_organisation', models.CharField(choices=[('entreprise', 'Entreprise'), ('association', 'Association'), ('independant', 'Indépendant')], max_length=20)),
                ('matricule_fiscal', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=500)),
                ('telephone_pro', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('site_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_organisateurs/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('categories_prevues', models.ManyToManyField(blank=True, related_name='demandes_organisateurs', to='events.categorie')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_organisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'organisateur",
                'verbose_name_plural': "Demandes d'organisateurs",
                'ordering': ['-date_demande'],
            },
        ),
    ]
