# Generated by Django 5.2.11 on 2026-09-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_notification'),
        ('users', '0006_alter_user_current_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interets',
            field=models.ManyToManyField(blank=True, related_name='users_interesses', to='events.categorie'),
        ),
    ]
